<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Deletar Contato?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h1>
                    <div id="personName"></div>
                </h1>
            </div>
            <div class="modal-footer">
                <form method="POST" action="" accept-charset="UTF-8" id="deleteForm">
                    <input name="_method" type="hidden" value="DELETE">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-danger">Deletar</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="application/javascript">
    function personDelete(id, name) {
        $('#personName').html(name);
        $('#deleteForm').attr('action', '<?= 'phonebook/delete?id=' ?>' + id);
    }
</script>