<?php
$phonebook = $this->views->phonebook;
?>


<br/>
<div class="row">
    <div class="col-sm-12">


        <form method="POST" action="update" accept-charset="UTF-8">
            <?php include_once 'App/Views/phonebook/partials/form-inputs.phtml' ?>

            <button type="submit" class="btn btn-primary">Salvar</button>

        </form>
    </div>
</div>

<script type="application/javascript">

    $(document).ready(function () {
        <?php $phonebook->getEmails(); ?>
        <?php foreach ($phonebook->getEmails() as $key => $value): ?>
        <?php if($key): ?>
        addEmail('<?= $value ?>');
        <?php endif; ?>
        <?php endforeach;?>

        <?php foreach ($phonebook->getPhones() as $key => $value): ?>
        <?php if($key): ?>
        addPhone('<?= $value ?>');
        <?php endif; ?>
        <?php endforeach;?>

        $('.phone_with_ddd').mask('(00) 0000-0000# ');
    });

    function removeEmail(element) {
        element.closest('.form-group').remove();
    }

    function addEmail(value) {
        const html =
            '<div class="form-group">'
            + '<div class="input-group">'
            + '<input type="email" name="emails[]" value="' + value + '" class="form-control col-sm-12" placeholder="Email">'
            + '<div class="input-group-append">'
            + '<div class="input-group-text" style="background: darkred; color: #fff" onclick="removeEmail($(this))">'
            + 'Remover</div>'
            + '</div>'
            + '</div>';

        $('#emails').append(html);
    }

    function removePhone(element) {
        element.closest('.form-group').remove();
    }

    function addPhone(value) {
        const html =
            '<div class="form-group">'
            + '<div class="input-group">'
            + '<input type="text" name="phones[]" value="' + value + '" class="form-control col-sm-12 phone_with_ddd" placeholder="Telefone">'
            + '<div class="input-group-append">'
            + '<div class="input-group-text" style="background: darkred; color: #fff" onclick="removePhone($(this))">'
            + 'Remover</div>'
            + '</div>'
            + '</div>';

        $('#phones').append(html);
        $('.phone_with_ddd').mask('(00) 0000-0000# ');
    }
</script>
