<br/>

<div class="row">
    <div class="col-sm-12">
        <a href="phonebook/create" class="btn btn-sm btn-success float-right">Cadastrar</a>
    </div>
</div>

<br>

<div class="row justify-content-center">
    <div class="col-md-12">
        <table class="table" id="myTable">
            <thead>
            <tr>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Telefones</th>
                <th>Emails</th>
                <th>Ação</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>


<script type="application/javascript">
    $(document).ready(function () {
        $('#myTable').DataTable({
            "ajax": "phonebook/json"
        });
    });
</script>

<?php require_once 'delete.phtml'; ?>

