<br/>
<?php
$phonebook = $this->views->phonebook;
?>
<style>
    .button-add, .button-remove, .first-phone-line, .first-email-line{
        display: none;
    }
</style>

<div class="row">
    <div class="col-sm-12">
        <form method="POST" action="store" accept-charset="UTF-8 ">
            <?php include_once 'App/Views/phonebook/partials/form-inputs.phtml' ?>
            <script type="application/javascript">
                $(document).ready(function () {
                    $("#phonebook-form :input").prop("disabled", true);
                    <?php foreach ($phonebook->getEmails() as $key=>$email) : ?>
                        addEmail('<?= $email; ?>');
                        $("#phonebook-form :input").prop("disabled", true);
                    <?php endforeach; ?>
                    <?php foreach ($phonebook->getPhones() as $phone) : ?>
                        addPhone('<?= $phone; ?>');
                        $("#phonebook-form :input").prop("disabled", true);
                    <?php endforeach; ?>
                });
            </script>
        </form>
    </div>
</div>
